---
category_id:
    - 52f2ab2ebcbc57f1066b8b4f # Bus Stop
    - 4bf58dd8d48988d1fe931735 # Bus Station
    - 4bf58dd8d48988d12b951735 # Bus Line
regex:
    base:
        "<Service> Bus Line": (?:(?P<service>.+) )?Bus (?P<type>Line)(?P<remainder>.*)$
        "<Service> Bus Stop": (?:(?P<service>.+) )?Bus (?P<type>Stop)(?P<remainder>.*)$
        "<Service> Stop": (?:(?P<service>.+) )?(?P<type>Stop)(?P<remainder>.*)$
        "<Service> Line": (?:(?P<service>.+) )?(?P<type>Line)(?P<remainder>.*)$
        "<Service>": (?:(?P<service>\w+) )?(?P<remainder>.*)$
    id:
        "<num>": (?P<stopid> ?)(?P<hash> ?#? ?)(?P<num>\d+) ?(?P<remainder>.*)$
        "ID <num>": (?P<stopid> ?)ID(?P<hash> ?#? ?)(?P<num>\d+) ?(?P<remainder>.*)$
    extra:
        "/ street & street": / ?(.*) & (.*)$
        "/ street and street": / ?(.*) and (.*)$
        "Nothing": ^$
ne: 
    lat: 45.59
    lon: -122.55
sw:
    lat: 45.45
    lon: -122.70
gridsize: 0.01
standardize:
    Bus Lines:
        match:
            type: Line
        format: "{service} Bus Line {num}"
        coalesce:
            - service
        category_id: 4bf58dd8d48988d12b951735
        defaults:
            service: TriMet
    Bus Stops:
        format: "{service} Stop ID {num}"
        coalesce:
            - service
        category_id: 52f2ab2ebcbc57f1066b8b4f
        defaults:
            service: TriMet

max_results: 50
